# Generated by Django 3.0.6 on 2020-09-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
