# Generated by Django 3.0.6 on 2020-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201007_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('designer', 'Designer'), ('developer', 'Developer'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
